setup(name='captionr',
      version='0.3.0',
      description='Multi-modal image captioning',
      url='https://github.com/theovercomer8/captionr',
      author='David Israel',
      author_email='theovercomer8@gmail.com',
      license='MIT',
      packages=['captionr'],
      zip_safe=False)